// Code generated by (shadowopera) archmage. DO NOT EDIT.

package conf

import (
	"github.com/shadowopera/sdk-go/archmage"
)

type (
	Duration = archmage.Duration
)

type (
	Ref[V int | string, T any] = archmage.Ref[V, T]
)

func makeRef[V int | string, T any](v V, r T) Ref[V, T] {
	return Ref[V, T]{v, r}
}

type (
	Tuple1[T1 any]                         = archmage.Tuple1[T1]
	Tuple2[T1, T2 any]                     = archmage.Tuple2[T1, T2]
	Tuple3[T1, T2, T3 any]                 = archmage.Tuple3[T1, T2, T3]
	Tuple4[T1, T2, T3, T4 any]             = archmage.Tuple4[T1, T2, T3, T4]
	Tuple5[T1, T2, T3, T4, T5 any]         = archmage.Tuple5[T1, T2, T3, T4, T5]
	Tuple6[T1, T2, T3, T4, T5, T6 any]     = archmage.Tuple6[T1, T2, T3, T4, T5, T6]
	Tuple7[T1, T2, T3, T4, T5, T6, T7 any] = archmage.Tuple7[T1, T2, T3, T4, T5, T6, T7]
)

type (
	Vec2[T comparable] = archmage.Vec2[T]
	Vec3[T comparable] = archmage.Vec3[T]
	Vec4[T comparable] = archmage.Vec4[T]
)

type (
	AtlasItem = archmage.AtlasItem
)
