// Code generated by (shadowopera) archmage. DO NOT EDIT.

package conf

import (
	"fmt"
	"maps"
	"slices"

	"shadop.dev/pkg/sdk-go/archmage"
)

var (
	_ archmage.Atlas = (*ConfigAtlas)(nil)
)

type ConfigAtlas struct {
	m map[string]*AtlasItem
	AtlasExtension

	VersionInfo map[string]any

	CharacterArray  CharacterArray
	GameCfg         GameCfg
	HeroTable       HeroTable
	ItemTable       ItemTable
	MagicTable      MagicTable
	Matrix2Table    Matrix2Table
	PropFloatsCfg   PropFloatsCfg
	RaceTable       RaceTable
	RefTable        RefTable
	StringTable     StringTable
	VtItemXTable    VtItemXTable
	VtSkillTable    VtSkillTable
	WeaponRuneTable WeaponRuneTable
}

func NewConfigAtlas() *ConfigAtlas {
	var atlas ConfigAtlas
	atlas.buildMap()
	return &atlas
}

func (atlas *ConfigAtlas) buildMap() {
	atlas.m = map[string]*AtlasItem{
		"character":   {Cfg: &atlas.CharacterArray, Mapping: "unique"},
		"game":        {Cfg: &atlas.GameCfg, Mapping: "single"},
		"hero":        {Cfg: &atlas.HeroTable, Mapping: "unique"},
		"Item":        {Cfg: &atlas.ItemTable, Mapping: "unique"},
		"Magic":       {Cfg: &atlas.MagicTable, Mapping: "unique"},
		"matrix2":     {Cfg: &atlas.Matrix2Table, Mapping: "unique"},
		"prop_floats": {Cfg: &atlas.PropFloatsCfg, Mapping: "single"},
		"Race":        {Cfg: &atlas.RaceTable, Mapping: "unique"},
		"ref":         {Cfg: &atlas.RefTable, Mapping: "unique"},
		"string":      {Cfg: &atlas.StringTable, Mapping: "unique"},
		"vtItemX":     {Cfg: &atlas.VtItemXTable, Mapping: "multiple"},
		"vtSkill":     {Cfg: &atlas.VtSkillTable, Mapping: "multiple"},
		"weapon-rune": {Cfg: &atlas.WeaponRuneTable, Mapping: "unique"},
	}
}

func (atlas *ConfigAtlas) SetVersionInfo(verInfo map[string]any) {
	atlas.VersionInfo = verInfo
}

type refBinder interface {
	bindRefs(atlas *ConfigAtlas)
}

func (atlas *ConfigAtlas) BindRefs() {
	for _, k := range slices.Sorted(maps.Keys(atlas.m)) {
		cfg, ok := atlas.m[k].Cfg.(refBinder)
		if ok && cfg != nil {
			cfg.bindRefs(atlas)
		}
	}
}

func (atlas *ConfigAtlas) AtlasItems() map[string]*AtlasItem {
	return atlas.m
}

func genericLookup[V comparable, R any](cfgID V, tbl map[V]R, tblName string) (R, error) {
	var zero R
	if cfgID == *new(V) {
		return zero, nil
	}
	if e, ok := tbl[cfgID]; ok {
		return e, nil
	}

	err := fmt.Errorf("%s: config entry not found for ID %v", tblName, cfgID)
	return zero, err
}

func genericMustLookup[V comparable, R any](cfgID V, tbl map[V]R, tblName string) R {
	e, err := genericLookup(cfgID, tbl, tblName)
	if err != nil {
		panic(err)
	}
	return e
}

func init() {
	m := make(map[string]bool)
	m["Rab"] = true // string
	if len(m) != 1 {
		panic("conflicting pubtype detected")
	}
}
