// Code generated by (shadowopera) archmage. DO NOT EDIT.

package conf

import (
	"fmt"
	"maps"
	"slices"
)

type ConfigAtlas struct {
	m map[string]*AtlasItem
	AtlasExtension

	CharactersArray  CharactersArray
	GameCfg          GameCfg
	HeroesTable      HeroesTable
	ItemsTable       ItemsTable
	MagicsTable      MagicsTable
	Matrix2Table     Matrix2Table
	PropFloatsCfg    PropFloatsCfg
	RacesTable       RacesTable
	RefTable         RefTable
	StringTable      StringTable
	WeaponRunesTable WeaponRunesTable
}

func NewConfigAtlas() *ConfigAtlas {
	var atlas ConfigAtlas
	atlas.buildMap()
	return &atlas
}

func (atlas *ConfigAtlas) buildMap() {
	atlas.m = map[string]*AtlasItem{
		"characters":   {Cfg: &atlas.CharactersArray, Arity: "single"},
		"game":         {Cfg: &atlas.GameCfg, Arity: "multiple"},
		"heroes":       {Cfg: &atlas.HeroesTable, Arity: "single"},
		"Items":        {Cfg: &atlas.ItemsTable, Arity: "single"},
		"Magics":       {Cfg: &atlas.MagicsTable, Arity: "single"},
		"matrix2":      {Cfg: &atlas.Matrix2Table, Arity: "single"},
		"prop_floats":  {Cfg: &atlas.PropFloatsCfg, Arity: "multiple"},
		"Races":        {Cfg: &atlas.RacesTable, Arity: "single"},
		"ref":          {Cfg: &atlas.RefTable, Arity: "single"},
		"string":       {Cfg: &atlas.StringTable, Arity: "single"},
		"weapon-runes": {Cfg: &atlas.WeaponRunesTable, Arity: "single"},
	}
}

type refBinder interface {
	bindRefs(atlas *ConfigAtlas)
}

func (atlas *ConfigAtlas) BindRefs() {
	for _, k := range slices.Sorted(maps.Keys(atlas.m)) {
		cfg, ok := atlas.m[k].Cfg.(refBinder)
		if ok && cfg != nil {
			cfg.bindRefs(atlas)
		}
	}
}

func (atlas *ConfigAtlas) AtlasItems() map[string]*AtlasItem {
	return atlas.m
}

func genericLookup[V comparable, R any](cfgID V, tbl map[V]R, tblName string) (R, error) {
	var zero R
	if cfgID == *new(V) {
		return zero, nil
	}
	if e, ok := tbl[cfgID]; ok {
		return e, nil
	}

	err := fmt.Errorf("%s: config entry with ID %v not found", tblName, cfgID)
	return zero, err
}

func genericMustLookup[V comparable, R any](cfgID V, tbl map[V]R, tblName string) R {
	e, err := genericLookup(cfgID, tbl, tblName)
	if err != nil {
		panic(err)
	}
	return e
}

func init() {
	m := make(map[string]bool)
	m["Rab"] = true // string
	if len(m) != 1 {
		panic("conflicting pubtype detected")
	}
}
