// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/character.json5

package conf

type CharacterArray []*CharacterCfg

type CharacterCfg struct {
	ID            string                    `json:"id"`
	Name          L10n                      `json:"name"`   // name config
	Race          Ref[string, RaceCfg]      `json:"race"`   // race config
	Health        int                       `json:"health"` // health config
	Attack        float64                   `json:"attack"`
	IsPlayable    bool                      `json:"isPlayable"`
	Skills        []string                  `json:"skills"`
	Runes         []Ref[int, WeaponRuneCfg] `json:"runes"` // my runes
	UltimateSkill int                       `json:"ultimateSkill"`
	RefCrude      *character_RefCrude       `json:"ref-crude"`
}

// character_RefCrude represents $.*['ref-crude']
type character_RefCrude struct {
	R1 int    `json:"r1"`
	R2 string `json:"r2"`
}

// region Trifles

func (x CharacterArray) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *CharacterCfg) bindRefs(atlas *ConfigAtlas) {
	x.Race.Ref = atlas.RaceTable.MustLookup(x.Race.RawValue)
	for i, v1 := range x.Runes {
		x.Runes[i].Ref = atlas.WeaponRuneTable.MustLookup(v1.RawValue)
	}
}

// endregion
