// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/characters.json

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type CharactersArray []*CharactersCfg

type CharactersCfg struct {
	ID         string                      `json:"id"`
	Name       L10n                        `json:"name"`   // name config
	Race       Ref[string, *RacesCfg]      `json:"race"`   // race config
	Health     int                         `json:"health"` // health config
	Attack     float64                     `json:"attack"`
	IsPlayable bool                        `json:"isPlayable"`
	Skills     []string                    `json:"skills"`
	RefCrude   *characters_RefCrude        `json:"ref-crude"`
	Runes      []Ref[int, *WeaponRunesCfg] `json:"runes"` // my runes
}

// characters_RefCrude represents $.*['ref-crude']
type characters_RefCrude struct {
	R1 int    `json:"r1"`
	R2 string `json:"r2"`
}

// region Trifles

func (x *CharactersArray) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyArrayOverride(x, data)
}

func (x CharactersArray) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *CharactersCfg) bindRefs(atlas *ConfigAtlas) {
	x.Race.Ref = atlas.RacesTable.MustLookup(x.Race.RawValue)
	for i, v1 := range x.Runes {
		x.Runes[i].Ref = atlas.WeaponRunesTable.MustLookup(v1.RawValue)
	}
}

// endregion
