// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/game.xlsx

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type GameCfg struct {
	XInt      int                           `json:"x-int"`      // desc-x-int
	XInt32    int32                         `json:"x-int32"`    // desc-x-int32
	XFloat64  float64                       `json:"x-float64"`  // desc-x-float64
	XString   string                        `json:"x-string"`   // desc-x-string
	XBool     bool                          `json:"x-bool"`     // desc-x-bool
	XDuration Duration                      `json:"x-duration"` // desc-x-duration
	XPath     string                        `json:"x-path"`     // desc-x-path
	XDatetime time.Time                     `json:"x-datetime"` // desc-x-datetime
	XRef      Ref[int, *WeaponRunesCfg]     `json:"x-ref"`      // desc-x-ref
	XL10n     L10n                          `json:"x-l10n"`     // desc-x-l10n
	XArray1   []int                         `json:"x-array1"`   // desc-x-array1
	XArray2   []int8                        `json:"x-array2"`   // desc-x-array2
	XMap      map[int]string                `json:"x-map"`      // desc-x-map
	XObject   *game_XObject                 `json:"x-object"`   // desc-x-object
	XTuple    *Tuple3[int, float32, string] `json:"x-tuple"`    // desc-x-tuple
	XVector   Vec3[int32]                   `json:"x-vector"`   // desc-x-vector
}

// game_XObject represents $['x-object']
type game_XObject struct {
	FieldX int    `json:"fieldX"`
	FieldY string `json:"fieldY"`
}

// region Trifles

var (
	_GameCfgFields = map[string]int8{
		"x-int":      1,
		"x-int32":    1,
		"x-float64":  1,
		"x-string":   1,
		"x-bool":     1,
		"x-duration": 1,
		"x-path":     1,
		"x-datetime": 1,
		"x-ref":      1,
		"x-l10n":     1,
		"x-array1":   1,
		"x-array2":   1,
		"x-map":      2,
		"x-object":   3,
		"x-tuple":    1,
		"x-vector":   1,
	}
	_GameCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[GameCfg](
		_GameCfgFields,
	)
)

func (x *GameCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "GameCfg", _GameCfgFields, _GameCfgFieldIndexMap)
}

var (
	_game_XObjectFields = map[string]int8{
		"fieldX": 1,
		"fieldY": 1,
	}
	_game_XObjectFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[game_XObject](
		_game_XObjectFields,
	)
)

func (x *game_XObject) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "game_XObject", _game_XObjectFields, _game_XObjectFieldIndexMap)
}

func (x *GameCfg) bindRefs(atlas *ConfigAtlas) {
	x.XRef.Ref = atlas.WeaponRunesTable.MustLookup(x.XRef.RawValue)
}

// endregion
