// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/hero.xlsx

package conf

type HeroTable map[int]*HeroCfg

type HeroCfg struct {
	ID                  int                    `json:"-"`
	HeroName            L10n                   `json:"heroName"`
	StartLevel          int                    `json:"startLevel"`
	Referrer            []Ref[int, RefCfg]     `json:"referrer"`
	RaceCombo           []*hero_RaceComboEntry `json:"race-combo"`
	ReferrerSort        []Ref[int, RefCfg]     `json:"referrer-sort"`
	ReferrerCompact     []Ref[int, RefCfg]     `json:"referrer-compact"`
	ReferrerSortCompact []Ref[int, RefCfg]     `json:"referrer-sort-compact"`
}

// hero_RaceComboEntry represents $.*['race-combo'].*
type hero_RaceComboEntry struct {
	Race1 Ref[string, RaceCfg] `json:"race1"`
	Race2 Ref[string, RaceCfg] `json:"race2"`
}

func (x HeroTable) TryLookup(cfgID int) (*HeroCfg, error) {
	return xTryLookup[int, *HeroCfg](cfgID, x, "HeroTable")
}

func (x HeroTable) Lookup(cfgID int) *HeroCfg {
	return xLookup[int, *HeroCfg](cfgID, x, "HeroTable")
}

// region Trifles

func (x HeroTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x HeroTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *HeroCfg) bindRefs(atlas *ConfigAtlas) {
	for i, ref := range x.Referrer {
		x.Referrer[i].Ref = atlas.RefTable.Lookup(ref.RawValue)
	}
	for _, v1 := range x.RaceCombo {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
	for i, ref := range x.ReferrerSort {
		x.ReferrerSort[i].Ref = atlas.RefTable.Lookup(ref.RawValue)
	}
	for i, ref := range x.ReferrerCompact {
		x.ReferrerCompact[i].Ref = atlas.RefTable.Lookup(ref.RawValue)
	}
	for i, ref := range x.ReferrerSortCompact {
		x.ReferrerSortCompact[i].Ref = atlas.RefTable.Lookup(ref.RawValue)
	}
}

func (x *hero_RaceComboEntry) bindRefs(atlas *ConfigAtlas) {
	x.Race1.Ref = atlas.RaceTable.Lookup(x.Race1.RawValue)
	x.Race2.Ref = atlas.RaceTable.Lookup(x.Race2.RawValue)
}

// endregion
