// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/heroes.xlsx

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type HeroesTable map[int]*HeroesCfg

type HeroesCfg struct {
	ID                  int                      `json:"-"`
	HeroName            L10n                     `json:"heroName"`
	StartLevel          int                      `json:"startLevel"`
	Referrer            []Ref[int, *RefCfg]      `json:"referrer"`
	RaceCombo           []*heroes_RaceComboEntry `json:"race-combo"`
	ReferrerSort        []Ref[int, *RefCfg]      `json:"referrer-sort"`
	ReferrerCompact     []Ref[int, *RefCfg]      `json:"referrer-compact"`
	ReferrerSortCompact []Ref[int, *RefCfg]      `json:"referrer-sort-compact"`
}

// heroes_RaceComboEntry represents $.*['race-combo'].*
type heroes_RaceComboEntry struct {
	Race1 Ref[string, *RacesCfg] `json:"race1"`
	Race2 Ref[string, *RacesCfg] `json:"race2"`
}

func (x HeroesTable) Lookup(cfgID int) (*HeroesCfg, error) {
	return genericLookup[int, *HeroesCfg](cfgID, x, "HeroesTable")
}

func (x HeroesTable) MustLookup(cfgID int) *HeroesCfg {
	return genericMustLookup[int, *HeroesCfg](cfgID, x, "HeroesTable")
}

// region Trifles

func (x HeroesTable) ApplyKeys() {
	for k, v := range x {
		v.ID = k
	}
}

func (x *HeroesTable) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyMapValueOverride(x, data)
}

var (
	_HeroesCfgFields = map[string]int8{
		"id":                    1,
		"heroName":              1,
		"startLevel":            1,
		"referrer":              1,
		"race-combo":            1,
		"referrer-sort":         1,
		"referrer-compact":      1,
		"referrer-sort-compact": 1,
	}
	_HeroesCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[HeroesCfg](
		_HeroesCfgFields,
	)
)

func (x *HeroesCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "HeroesCfg", _HeroesCfgFields, _HeroesCfgFieldIndexMap)
}

func (x HeroesTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *HeroesCfg) bindRefs(atlas *ConfigAtlas) {
	for i, ref := range x.Referrer {
		x.Referrer[i].Ref = atlas.RefTable.MustLookup(ref.RawValue)
	}
	for _, v1 := range x.RaceCombo {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
	for i, ref := range x.ReferrerSort {
		x.ReferrerSort[i].Ref = atlas.RefTable.MustLookup(ref.RawValue)
	}
	for i, ref := range x.ReferrerCompact {
		x.ReferrerCompact[i].Ref = atlas.RefTable.MustLookup(ref.RawValue)
	}
	for i, ref := range x.ReferrerSortCompact {
		x.ReferrerSortCompact[i].Ref = atlas.RefTable.MustLookup(ref.RawValue)
	}
}

func (x *heroes_RaceComboEntry) bindRefs(atlas *ConfigAtlas) {
	x.Race1.Ref = atlas.RacesTable.MustLookup(x.Race1.RawValue)
	x.Race2.Ref = atlas.RacesTable.MustLookup(x.Race2.RawValue)
}

// endregion
