// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Items

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type ItemsTable map[int]*ItemsCfg

type ItemsCfg struct {
	ID    int          `json:"-"`
	Name  string       `json:"name"`
	Price *items_Price `json:"price"`
}

// items_Price represents $.*.price
type items_Price struct {
	One   int `json:"one"`
	Stack int `json:"stack"`
}

func (x ItemsTable) Lookup(cfgID int) (*ItemsCfg, error) {
	return genericLookup[int, *ItemsCfg](cfgID, x, "ItemsTable")
}

func (x ItemsTable) MustLookup(cfgID int) *ItemsCfg {
	return genericMustLookup[int, *ItemsCfg](cfgID, x, "ItemsTable")
}

// region Trifles

func (x ItemsTable) ApplyKeys() {
	for k, v := range x {
		v.ID = k
	}
}

func (x *ItemsTable) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyMapValueOverride(x, data)
}

var (
	_ItemsCfgFields = map[string]int8{
		"id":    1,
		"name":  1,
		"price": 3,
	}
	_ItemsCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[ItemsCfg](
		_ItemsCfgFields,
	)
)

func (x *ItemsCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "ItemsCfg", _ItemsCfgFields, _ItemsCfgFieldIndexMap)
}

var (
	_items_PriceFields = map[string]int8{
		"one":   1,
		"stack": 1,
	}
	_items_PriceFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[items_Price](
		_items_PriceFields,
	)
)

func (x *items_Price) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "items_Price", _items_PriceFields, _items_PriceFieldIndexMap)
}

// endregion
