// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Item

package conf

type ItemTable map[int]*ItemCfg

type ItemCfg struct {
	ID    int         `json:"-"`
	Name  string      `json:"name"`
	Price *item_Price `json:"price"`
}

// item_Price represents $.*.price
type item_Price struct {
	One   int `json:"one"`
	Stack int `json:"stack"`
}

func (x ItemTable) Lookup(cfgID int) (*ItemCfg, error) {
	return genericLookup[int, *ItemCfg](cfgID, x, "ItemTable")
}

func (x ItemTable) MustLookup(cfgID int) *ItemCfg {
	return genericMustLookup[int, *ItemCfg](cfgID, x, "ItemTable")
}

// region Trifles

func (x ItemTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
