// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Items

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type ItemsTable map[int]*ItemsCfg

type ItemsCfg struct {
	ID    int          `json:"-"`
	Name  string       `json:"name"`
	Price *items_Price `json:"price"`
}

// items_Price represents $.*.price
type items_Price struct {
	One   int `json:"one"`
	Stack int `json:"stack"`
}

func (x ItemsTable) Lookup(cfgID int) (*ItemsCfg, error) {
	return genericLookup[int, *ItemsCfg](cfgID, x, "ItemsTable")
}

func (x ItemsTable) MustLookup(cfgID int) *ItemsCfg {
	return genericMustLookup[int, *ItemsCfg](cfgID, x, "ItemsTable")
}

// region Trifles

func (x ItemsTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
