// Code generated by (shadowopera) archmage. DO NOT EDIT.

package conf

import (
	"golang.org/x/text/language"
	"shadop.dev/pkg/sdk-go/archmage"
)

var (
	// GetI18n must be set before calling any i18n-related functions.
	GetI18n func() *archmage.I18n
)

type L10n string

func (l L10n) GetText(lang language.Tag) (string, error) {
	return GetI18n().GetText(string(l), lang)
}

func (l L10n) Text(lang language.Tag) string {
	return GetI18n().Text(string(l), lang)
}
