// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Magics

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type MagicsTable map[int]*MagicsCfg

type MagicsCfg struct {
	ID   int    `json:"-"`
	Name string `json:"name"`
}

func (x MagicsTable) Lookup(cfgID int) (*MagicsCfg, error) {
	return genericLookup[int, *MagicsCfg](cfgID, x, "MagicsTable")
}

func (x MagicsTable) MustLookup(cfgID int) *MagicsCfg {
	return genericMustLookup[int, *MagicsCfg](cfgID, x, "MagicsTable")
}

// region Trifles

func (x MagicsTable) ApplyKeys() {
	for k, v := range x {
		v.ID = k
	}
}

func (x *MagicsTable) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyMapValueOverride(x, data)
}

var (
	_MagicsCfgFields = map[string]int8{
		"id":   1,
		"name": 1,
	}
	_MagicsCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[MagicsCfg](
		_MagicsCfgFields,
	)
)

func (x *MagicsCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "MagicsCfg", _MagicsCfgFields, _MagicsCfgFieldIndexMap)
}

// endregion
