// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Magic

package conf

type MagicTable map[int]*MagicCfg

type MagicCfg struct {
	ID   int    `json:"-"`
	Name string `json:"name"`
}

func (x MagicTable) TryLookup(cfgID int) (*MagicCfg, error) {
	return xTryLookup[int, *MagicCfg](cfgID, x, "MagicTable")
}

func (x MagicTable) Lookup(cfgID int) *MagicCfg {
	return xLookup[int, *MagicCfg](cfgID, x, "MagicTable")
}

// region Trifles

func (x MagicTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
