// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Magics

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type MagicsTable map[int]*MagicsCfg

type MagicsCfg struct {
	ID   int    `json:"-"`
	Name string `json:"name"`
}

func (x MagicsTable) Lookup(cfgID int) (*MagicsCfg, error) {
	return genericLookup[int, *MagicsCfg](cfgID, x, "MagicsTable")
}

func (x MagicsTable) MustLookup(cfgID int) *MagicsCfg {
	return genericMustLookup[int, *MagicsCfg](cfgID, x, "MagicsTable")
}

// region Trifles

func (x MagicsTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
