// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/matrix2.json

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type Matrix2Table map[string]map[string][][]Ref[int, *HeroesCfg]

// region Trifles

func (x Matrix2Table) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		for _, v2 := range v1 {
			for _, v3 := range v2 {
				for i, v4 := range v3 {
					v3[i].Ref = atlas.HeroesTable.MustLookup(v4.RawValue)
				}
			}
		}
	}
}

// endregion
