// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/prop_floats.xlsx

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type PropFloatsCfg struct {
	B float64 `json:"B"` // desc-B
	C float32 `json:"C"` // desc-C
	D float64 `json:"D"` // desc-D
	E float32 `json:"E"` // desc-E
	F float64 `json:"F"` // desc-F
	G float64 `json:"G"` // desc-G
}

// region Trifles

var (
	_PropFloatsCfgFields = map[string]int8{
		"B": 1,
		"C": 1,
		"D": 1,
		"E": 1,
		"F": 1,
		"G": 1,
	}
	_PropFloatsCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[PropFloatsCfg](
		_PropFloatsCfgFields,
	)
)

func (x *PropFloatsCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "PropFloatsCfg", _PropFloatsCfgFields, _PropFloatsCfgFieldIndexMap)
}

// endregion
