// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/prop_floats.xlsx

package conf

import (
	"time"
)

var (
	_ *time.Time
)

type PropFloatsCfg struct {
	B float64 `json:"B"` // desc-B
	C float32 `json:"C"` // desc-C
	D float64 `json:"D"` // desc-D
	E float32 `json:"E"` // desc-E
	F float64 `json:"F"` // desc-F
	G float64 `json:"G"` // desc-G
}

// region Trifles

// endregion
