// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Races

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type RacesTable map[string]*RacesCfg

type RacesCfg struct {
	ID         string                  `json:"-"`
	Birthplace L10n                    `json:"birthplace"`
	Referrer1  Ref[int, *RefCfg]       `json:"referrer1"`
	Referrer2  Ref[string, *StringCfg] `json:"referrer2"`
	Heroes1    []Ref[int, *HeroesCfg]  `json:"heroes1"`
	Heroes2    []Ref[int, *HeroesCfg]  `json:"heroes2"`
}

func (x RacesTable) Lookup(cfgID string) (*RacesCfg, error) {
	return genericLookup[string, *RacesCfg](cfgID, x, "RacesTable")
}

func (x RacesTable) MustLookup(cfgID string) *RacesCfg {
	return genericMustLookup[string, *RacesCfg](cfgID, x, "RacesTable")
}

// region Trifles

func (x RacesTable) ApplyKeys() {
	for k, v := range x {
		v.ID = k
	}
}

func (x *RacesTable) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyMapValueOverride(x, data)
}

var (
	_RacesCfgFields = map[string]int8{
		"id":         1,
		"birthplace": 1,
		"referrer1":  1,
		"referrer2":  1,
		"heroes1":    1,
		"heroes2":    1,
	}
	_RacesCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[RacesCfg](
		_RacesCfgFields,
	)
)

func (x *RacesCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "RacesCfg", _RacesCfgFields, _RacesCfgFieldIndexMap)
}

func (x RacesTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RacesCfg) bindRefs(atlas *ConfigAtlas) {
	x.Referrer1.Ref = atlas.RefTable.MustLookup(x.Referrer1.RawValue)
	x.Referrer2.Ref = atlas.StringTable.MustLookup(x.Referrer2.RawValue)
	for i, ref := range x.Heroes1 {
		x.Heroes1[i].Ref = atlas.HeroesTable.MustLookup(ref.RawValue)
	}
	for i, ref := range x.Heroes2 {
		x.Heroes2[i].Ref = atlas.HeroesTable.MustLookup(ref.RawValue)
	}
}

// endregion
