// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Race

package conf

type RaceTable map[string]*RaceCfg

type RaceCfg struct {
	ID         string                 `json:"-"`
	Birthplace L10n                   `json:"birthplace"`
	Referrer1  Ref[int, RefCfg]       `json:"referrer1"`
	Referrer2  Ref[string, StringCfg] `json:"referrer2"`
	Heroes1    []Ref[int, HeroCfg]    `json:"heroes1"`
	Heroes2    []Ref[int, HeroCfg]    `json:"heroes2"`
}

func (x RaceTable) TryLookup(cfgID string) (*RaceCfg, error) {
	return xTryLookup[string, *RaceCfg](cfgID, x, "RaceTable")
}

func (x RaceTable) Lookup(cfgID string) *RaceCfg {
	return xLookup[string, *RaceCfg](cfgID, x, "RaceTable")
}

// region Trifles

func (x RaceTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x RaceTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RaceCfg) bindRefs(atlas *ConfigAtlas) {
	x.Referrer1.Ref = atlas.RefTable.Lookup(x.Referrer1.RawValue)
	x.Referrer2.Ref = atlas.StringTable.Lookup(x.Referrer2.RawValue)
	for i, ref := range x.Heroes1 {
		x.Heroes1[i].Ref = atlas.HeroTable.Lookup(ref.RawValue)
	}
	for i, ref := range x.Heroes2 {
		x.Heroes2[i].Ref = atlas.HeroTable.Lookup(ref.RawValue)
	}
}

// endregion
