// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/ref.xlsx

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type RefTable map[int]*RefCfg

type RefCfg struct {
	ID int                       `json:"-"`
	B  Ref[int, *WeaponRunesCfg] `json:"B"` // desc-B
	C  int                       `json:"C"` // desc-C
	D  Ref[int, *ItemsCfg]       `json:"D"` // desc-D
	E  Ref[int, *MagicsCfg]      `json:"E"` // desc-E
	F  Ref[string, *RacesCfg]    `json:"F"` // desc-F
	G  Ref[int, *HeroesCfg]      `json:"G"` // desc-G
	H  []Ref[string, *StringCfg] `json:"H"` // desc-H
	J  Ref[int, *ItemsCfg]       `json:"J"` // desc-J
	K  Ref[string, *RacesCfg]    `json:"K"` // desc-K
}

func (x RefTable) Lookup(cfgID int) (*RefCfg, error) {
	return genericLookup[int, *RefCfg](cfgID, x, "RefTable")
}

func (x RefTable) MustLookup(cfgID int) *RefCfg {
	return genericMustLookup[int, *RefCfg](cfgID, x, "RefTable")
}

// region Trifles

func (x RefTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x RefTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RefCfg) bindRefs(atlas *ConfigAtlas) {
	x.B.Ref = atlas.WeaponRunesTable.MustLookup(x.B.RawValue)
	x.D.Ref = atlas.ItemsTable.MustLookup(x.D.RawValue)
	x.E.Ref = atlas.MagicsTable.MustLookup(x.E.RawValue)
	x.F.Ref = atlas.RacesTable.MustLookup(x.F.RawValue)
	x.G.Ref = atlas.HeroesTable.MustLookup(x.G.RawValue)
	for i, v1 := range x.H {
		x.H[i].Ref = atlas.StringTable.MustLookup(v1.RawValue)
	}
	x.J.Ref = atlas.ItemsTable.MustLookup(x.J.RawValue)
	x.K.Ref = atlas.RacesTable.MustLookup(x.K.RawValue)
}

// endregion
