// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/string.xlsx

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type StringTable map[string]*StringCfg

type StringCfg struct {
	ID             string                 `json:"-"`
	B              *string_B              `json:"B"`
	E              string                 `json:"E"`               // desc-E
	DefValidate    string                 `json:"def-validate"`    // def-validate
	DefPostprocess string                 `json:"def-postprocess"` // def-postprocess
	I              string                 `json:"I"`               // desc-I
	K              Ref[string, *RacesCfg] `json:"K"`               // desc-K
	Referer1       Ref[int, *RefCfg]      `json:"referer1"`        // desc-referer1
	Referer2       Ref[int, *RefCfg]      `json:"referer2"`        // desc-referer2
	RefererN       []Ref[int, *RefCfg]    `json:"referer-n"`       // desc-referer-n
}

// string_B represents $.*.B
type string_B struct {
	Bar *Rab   `json:"bar"`
	Car string `json:"car"` // desc-B.car
}

// Rab represents $.*.B.bar
type Rab struct {
	Foo string `json:"foo"` // desc-B.bar.foo
	Qux string `json:"qux"` // desc-B.bar.qux
}

func (x StringTable) Lookup(cfgID string) (*StringCfg, error) {
	return genericLookup[string, *StringCfg](cfgID, x, "StringTable")
}

func (x StringTable) MustLookup(cfgID string) *StringCfg {
	return genericMustLookup[string, *StringCfg](cfgID, x, "StringTable")
}

// region Trifles

func (x StringTable) ApplyKeys() {
	for k, v := range x {
		v.ID = k
	}
}

func (x *StringTable) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyMapValueOverride(x, data)
}

var (
	_StringCfgFields = map[string]int8{
		"id":              1,
		"B":               3,
		"E":               1,
		"def-validate":    1,
		"def-postprocess": 1,
		"I":               1,
		"K":               1,
		"referer1":        1,
		"referer2":        1,
		"referer-n":       1,
	}
	_StringCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[StringCfg](
		_StringCfgFields,
	)
)

func (x *StringCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "StringCfg", _StringCfgFields, _StringCfgFieldIndexMap)
}

var (
	_string_BFields = map[string]int8{
		"bar": 3,
		"car": 1,
	}
	_string_BFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[string_B](
		_string_BFields,
	)
)

func (x *string_B) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "string_B", _string_BFields, _string_BFieldIndexMap)
}

var (
	_RabFields = map[string]int8{
		"foo": 1,
		"qux": 1,
	}
	_RabFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[Rab](
		_RabFields,
	)
)

func (x *Rab) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "Rab", _RabFields, _RabFieldIndexMap)
}

func (x StringTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *StringCfg) bindRefs(atlas *ConfigAtlas) {
	x.K.Ref = atlas.RacesTable.MustLookup(x.K.RawValue)
	x.Referer1.Ref = atlas.RefTable.MustLookup(x.Referer1.RawValue)
	x.Referer2.Ref = atlas.RefTable.MustLookup(x.Referer2.RawValue)
	for i, ref := range x.RefererN {
		x.RefererN[i].Ref = atlas.RefTable.MustLookup(ref.RawValue)
	}
}

// endregion
