// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtItemX (virtual table)

package conf

type VtItemXTable map[int]*VtItemXCfg

type VtItemXCfg struct {
	ID             int                            `json:"-"`
	Name           string                         `json:"name"`
	Price          int                            `json:"price"`
	Desc           string                         `json:"desc"`
	SpecialSkill   int                            `json:"special-skill"`
	Armor          float32                        `json:"armor"`
	Dps            float32                        `json:"dps"`
	ShieldSkills   []int                          `json:"shield-skills"`
	Power          float32                        `json:"power"`
	AttributeBonus []*vtItemX_AttributeBonusEntry `json:"attributeBonus"`
}

// vtItemX_AttributeBonusEntry represents $.*.attributeBonus.*
type vtItemX_AttributeBonusEntry struct {
	Attr  string `json:"attr"`
	Bonus int    `json:"bonus"`
}

func (x VtItemXTable) TryLookup(cfgID int) (*VtItemXCfg, error) {
	return xTryLookup[int, *VtItemXCfg](cfgID, x, "VtItemXTable")
}

func (x VtItemXTable) Lookup(cfgID int) *VtItemXCfg {
	return xLookup[int, *VtItemXCfg](cfgID, x, "VtItemXTable")
}

// region Trifles

func (x VtItemXTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
