// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtSkill (virtual table)

package conf

import (
	"time"
)

var (
	_ *time.Time
)

type VtSkillTable map[int]*VtSkillCfg

type VtSkillCfg struct {
	ID      int                       `json:"-"`
	Name    string                    `json:"name"`
	Class   string                    `json:"class"`
	Foo     map[int]*vtSkill_FooEntry `json:"Foo"`
	Reagent int                       `json:"reagent"` // reagent
	Weapons []int                     `json:"weapons"`
}

// vtSkill_FooEntry represents $.*.Foo.*
type vtSkill_FooEntry struct {
	X1 string   `json:"X1"` // X1a
	X2 Duration `json:"X2"`
	X5 int      `json:"X5"` // X5
}

func (x VtSkillTable) Lookup(cfgID int) (*VtSkillCfg, error) {
	return genericLookup[int, *VtSkillCfg](cfgID, x, "VtSkillTable")
}

func (x VtSkillTable) MustLookup(cfgID int) *VtSkillCfg {
	return genericMustLookup[int, *VtSkillCfg](cfgID, x, "VtSkillTable")
}

// region Trifles

func (x VtSkillTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
