// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/weapon-rune.xlsx

package conf

type WeaponRuneTable map[int]*WeaponRuneCfg

type WeaponRuneCfg struct {
	ID       int    `json:"-"`
	RuneName string `json:"runeName"`
	Power    int    `json:"power"`
}

func (x WeaponRuneTable) Lookup(cfgID int) (*WeaponRuneCfg, error) {
	return genericLookup[int, *WeaponRuneCfg](cfgID, x, "WeaponRuneTable")
}

func (x WeaponRuneTable) MustLookup(cfgID int) *WeaponRuneCfg {
	return genericMustLookup[int, *WeaponRuneCfg](cfgID, x, "WeaponRuneTable")
}

// region Trifles

func (x WeaponRuneTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
