// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/weapon-runes.xlsx

package conf

import (
	"time"

	"github.com/shadowopera/sdk-go/archmage"
)

var (
	_ *time.Time
	_ *archmage.Duration
)

type WeaponRunesTable map[int]*WeaponRunesCfg

type WeaponRunesCfg struct {
	ID       int    `json:"-"`
	RuneName string `json:"runeName"`
	Power    int    `json:"power"`
}

func (x WeaponRunesTable) Lookup(cfgID int) (*WeaponRunesCfg, error) {
	return genericLookup[int, *WeaponRunesCfg](cfgID, x, "WeaponRunesTable")
}

func (x WeaponRunesTable) MustLookup(cfgID int) *WeaponRunesCfg {
	return genericMustLookup[int, *WeaponRunesCfg](cfgID, x, "WeaponRunesTable")
}

// region Trifles

func (x WeaponRunesTable) ApplyKeys() {
	for k, v := range x {
		v.ID = k
	}
}

func (x *WeaponRunesTable) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyMapValueOverride(x, data)
}

var (
	_WeaponRunesCfgFields = map[string]int8{
		"id":       1,
		"runeName": 1,
		"power":    1,
	}
	_WeaponRunesCfgFieldIndexMap = archmage.BuildJSONKeyToFieldIndexMap[WeaponRunesCfg](
		_WeaponRunesCfgFields,
	)
)

func (x *WeaponRunesCfg) ApplyOverride(data []byte) (Overridable, error) {
	return archmage.ApplyStructOverride(
		x, data, "WeaponRunesCfg", _WeaponRunesCfgFields, _WeaponRunesCfgFieldIndexMap)
}

// endregion
