[private]
list:
    @ just -l --unsorted

test:
    @ go test ./...

lint:
    go vet ./...

scc:
    @ command scc -x json --generated-markers 'Code generated by' --no-min-gen .

upgrade:
    @ go list -m -u -f '{{{{if and (not .Indirect) (.Update)}}{{{{.}}{{{{end}}' all | \
        rg --passthrough '\[.+?\]'
