// Code generated by (shadowopera) archmage. DO NOT EDIT.

package conf

import (
	_ "embed"
	"encoding/json/v2"

	"shadop.dev/pkg/sdk-go/archmage"
)

type (
	Duration = archmage.Duration
)

type (
	Ref[V int | string, T any] = archmage.Ref[V, T]
)

func makeRef[V int | string, T any](v V, r *T) Ref[V, T] {
	return Ref[V, T]{RawValue: v, Ref: r}
}

type (
	Tuple1[T0 any]                         = archmage.Tuple1[T0]
	Tuple2[T0, T1 any]                     = archmage.Tuple2[T0, T1]
	Tuple3[T0, T1, T2 any]                 = archmage.Tuple3[T0, T1, T2]
	Tuple4[T0, T1, T2, T3 any]             = archmage.Tuple4[T0, T1, T2, T3]
	Tuple5[T0, T1, T2, T3, T4 any]         = archmage.Tuple5[T0, T1, T2, T3, T4]
	Tuple6[T0, T1, T2, T3, T4, T5 any]     = archmage.Tuple6[T0, T1, T2, T3, T4, T5]
	Tuple7[T0, T1, T2, T3, T4, T5, T6 any] = archmage.Tuple7[T0, T1, T2, T3, T4, T5, T6]
)

type (
	Vec2[T comparable] = archmage.Vec2[T]
	Vec3[T comparable] = archmage.Vec3[T]
	Vec4[T comparable] = archmage.Vec4[T]
)

type (
	AtlasItem = archmage.AtlasItem
)

var (
	//go:embed version.json
	_codeVersion []byte
)

func CodeVersion() *archmage.VersionInfo {
	var info archmage.VersionInfo
	err := json.Unmarshal(_codeVersion, &info)
	if err != nil {
		panic(err)
	}
	return &info
}
