// Code generated by (shadowopera) archmage. DO NOT EDIT.

package conf

import (
	"cmp"
	"fmt"
	"maps"
	"slices"
	"strings"

	"shadop.dev/pkg/sdk-go/archmage"
)

var (
	_ archmage.Atlas = (*ConfigAtlas)(nil)
)

type ConfigAtlas struct {
	m map[string]*AtlasItem
	AtlasExtension

	DataVersion *archmage.VersionInfo

	CharacterArray  CharacterArray
	GameCfg         GameCfg
	HeroTable       HeroTable
	ItemTable       ItemTable
	MagicTable      MagicTable
	Matrix2Table    Matrix2Table
	PropFloatsCfg   PropFloatsCfg
	RaceTable       RaceTable
	RefTable        RefTable
	StringTable     StringTable
	VtItemXTable    VtItemXTable
	VtSkillTable    VtSkillTable
	WeaponRuneTable WeaponRuneTable
}

func NewConfigAtlas() *ConfigAtlas {
	var atlas ConfigAtlas
	atlas.buildMap()
	return &atlas
}

func (atlas *ConfigAtlas) buildMap() {
	atlas.m = map[string]*AtlasItem{
		"character":   {Cfg: &atlas.CharacterArray, Mapping: "unique"},
		"game":        {Cfg: &atlas.GameCfg, Mapping: "single"},
		"hero":        {Cfg: &atlas.HeroTable, Mapping: "unique"},
		"Item":        {Cfg: &atlas.ItemTable, Mapping: "unique"},
		"Magic":       {Cfg: &atlas.MagicTable, Mapping: "unique"},
		"matrix2":     {Cfg: &atlas.Matrix2Table, Mapping: "unique"},
		"prop_floats": {Cfg: &atlas.PropFloatsCfg, Mapping: "single"},
		"Race":        {Cfg: &atlas.RaceTable, Mapping: "unique"},
		"ref":         {Cfg: &atlas.RefTable, Mapping: "unique"},
		"string":      {Cfg: &atlas.StringTable, Mapping: "unique"},
		"vtItemX":     {Cfg: &atlas.VtItemXTable, Mapping: "multiple"},
		"vtSkill":     {Cfg: &atlas.VtSkillTable, Mapping: "multiple"},
		"weapon-rune": {Cfg: &atlas.WeaponRuneTable, Mapping: "unique"},
	}
}

func (atlas *ConfigAtlas) SetDataVersion(v *archmage.VersionInfo) {
	atlas.DataVersion = v
}

type refBinder interface {
	bindRefs(atlas *ConfigAtlas)
}

func (atlas *ConfigAtlas) BindRefs() {
	keys := slices.SortedFunc(maps.Keys(atlas.m), func(k1 string, k2 string) int {
		return cmp.Compare(strings.ToLower(k1), strings.ToLower(k2))
	})
	for _, k := range keys {
		cfg, ok := atlas.m[k].Cfg.(refBinder)
		if ok && cfg != nil {
			cfg.bindRefs(atlas)
		}
	}
}

func (atlas *ConfigAtlas) AtlasItems() map[string]*AtlasItem {
	return atlas.m
}

func (atlas *ConfigAtlas) OnLoaded() error {
	return atlas.AtlasExtension.OnLoaded(atlas)
}

func makeXRef[V int | string, T any](v V, r *T) XRef[V, T] {
	return XRef[V, T]{RawValue: v, Ref: r}
}

func xTryLookup[V comparable, R any](cfgID V, tbl map[V]R, tblName string) (R, error) {
	if e, ok := tbl[cfgID]; ok {
		return e, nil
	}

	err := fmt.Errorf("%s: config entry not found for ID %v", tblName, cfgID)
	return *new(R), err
}

func xLookup[V comparable, R any](cfgID V, tbl map[V]R, tblName string) R {
	var zero V
	if cfgID == zero {
		return *new(R)
	}
	e, err := xTryLookup(cfgID, tbl, tblName)
	if err != nil {
		panic(err)
	}
	return e
}

func init() {
	m := make(map[string]bool)
	m["Rab"] = true // string
	if len(m) != 1 {
		panic("conflicting pubtype detected")
	}
}
