// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/balance.xlsx

package conf

type BalanceCfg struct {
	// Enemy HP scale
	HpScale float32 `json:"hpScale"`
	// Enemy damage scale
	DmgScale float64 `json:"dmgScale"`
	// Gold bonus
	GoldBonus float64 `json:"goldBonus"`
	// Enemy level offset
	EnemyLevel int16 `json:"enemyLevel"`
	// Spawn interval
	SpawnInterval Duration `json:"spawnInterval"`
	// XP curve
	XpCurve []int32 `json:"xpCurve"`
}

// region Trifles

// endregion
