// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/chapter.json5

package conf

import "shadop.dev/pkg/sdk-go/internal/enums"

type ChapterArray []*ChapterCfg

type ChapterCfg struct {
	ID          string                           `json:"id"`
	Title       string                           `json:"title"`
	Hero        XRef[HeroCfgID, HeroCfg]         `json:"hero"`
	Monsters    []XRef[MonsterCfgID, MonsterCfg] `json:"monsters"`
	Recommended []enums.HeroClass                `json:"recommended"`
	TimeLimit   Duration                         `json:"timeLimit"`
	Waves       []int64                          `json:"waves"`
}

// region Trifles

func (x ChapterArray) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *ChapterCfg) bindRefs(atlas *ConfigAtlas) {
	x.Hero.Ref = atlas.HeroTable.Lookup(x.Hero.CfgID)
	for i, v1 := range x.Monsters {
		x.Monsters[i].Ref = atlas.MonsterTable.Lookup(v1.CfgID)
	}
}

// endregion
