// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/character.json5

package conf

type CharacterArray []*CharacterCfg

type CharacterCfg struct {
	ID string `json:"id"`
	// name config
	Name L10n `json:"name"`
	// race config
	Race XRef[RaceCfgID, RaceCfg] `json:"race"`
	// health config
	Health     int      `json:"health"`
	Attack     float64  `json:"attack"`
	IsPlayable bool     `json:"isPlayable"`
	Skills     []string `json:"skills"`
	// my runes
	Runes         []XRef[WeaponRuneCfgID, WeaponRuneCfg] `json:"runes"`
	UltimateSkill int64                                  `json:"ultimateSkill"`
	RefCrude      *character_RefCrude                    `json:"ref-crude"`
}

// character_RefCrude represents $.*['ref-crude']
type character_RefCrude struct {
	R1 int64  `json:"r1"`
	R2 string `json:"r2"`
}

// region Trifles

func (x CharacterArray) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *CharacterCfg) bindRefs(atlas *ConfigAtlas) {
	x.Race.Ref = atlas.RaceTable.Lookup(x.Race.CfgID)
	for i, v1 := range x.Runes {
		x.Runes[i].Ref = atlas.WeaponRuneTable.Lookup(v1.CfgID)
	}
}

// endregion
