// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/drop.xlsx

package conf

import "shadop.dev/pkg/sdk-go/internal/enums"

type DropCfgID int64

type DropTable map[DropCfgID]*DropCfg

type DropCfg struct {
	ID DropCfgID `json:"id"`
	// Drop name
	Name string `json:"name"`
	// Gold
	Gold MinMax[int32] `json:"gold"`
	// Bonus rate
	BonusRate MinMax[float32] `json:"bonusRate"`
	// Despawn time
	Despawn MinMax[Duration] `json:"despawn"`
	// Items
	Items *WeightedPool[XRef[ItemCfgID, ItemCfg]] `json:"items"`
	// Coins
	Coins *WeightedPool[int] `json:"coins"`
	// Titles
	Titles *WeightedPool[string] `json:"titles"`
	// Rarity
	Rarity *WeightedPool[enums.Rarity] `json:"rarity"`
	// Buff time
	BuffTime *WeightedPool[Duration] `json:"buffTime"`
}

func (x DropTable) TryLookup(cfgID DropCfgID) (*DropCfg, error) {
	return xTryLookup[DropCfgID, *DropCfg](cfgID, x, "DropTable")
}

func (x DropTable) Lookup(cfgID DropCfgID) *DropCfg {
	return xLookup[DropCfgID, *DropCfg](cfgID, x, "DropTable")
}

// region Trifles

func (x DropCfgID) Cfg() *DropCfg {
	return GetConfigAtlas().DropTable[x]
}

func (x DropTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x DropTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *DropCfg) bindRefs(atlas *ConfigAtlas) {
	if f := x.Items; f != nil {
		for i, ref := range f.Items {
			f.Items[i].Ref = atlas.ItemTable.Lookup(ref.CfgID)
		}
	}
}

// endregion
