// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/game.xlsx

package conf

import "time"
import "shadop.dev/pkg/sdk-go/internal/enums"

type GameCfg struct {
	// Game title
	Title L10n `json:"title"`
	// Max level
	MaxLevel int32 `json:"maxLevel"`
	// Starting hero
	StartHero XRef[HeroCfgID, HeroCfg] `json:"startHero"`
	// Server tick
	TickRate Duration `json:"tickRate"`
	// Background color
	BgColor RGBA `json:"bgColor"`
	// Launch date
	LaunchDate time.Time `json:"launchDate"`
	// Theme music
	Bgm string `json:"bgm"`
	// Starter items
	StarterItems []XRef[ItemCfgID, ItemCfg] `json:"starterItems"`
	// Daily resets
	DailyResets []Duration `json:"dailyResets"`
	// Allowed classes
	AllowedClasses []enums.HeroClass `json:"allowedClasses"`
	// Level caps
	LevelCaps []int `json:"levelCaps"`
	// Banned words
	BannedWords []string `json:"bannedWords"`
	// Bag slot sizes
	SlotSizes []int8 `json:"slotSizes"`
	// Level rewards
	LevelRewards map[int]XRef[ItemCfgID, ItemCfg] `json:"levelRewards"`
	// Tips
	Tips map[string]L10n `json:"tips"`
	// Class colors
	ClassColors map[enums.HeroClass]RGBA `json:"classColors"`
	// Features
	Features map[string]bool `json:"features"`
	// Message of the day
	Motd *Tuple1[string] `json:"motd"`
	// Boss spawn
	BossSpawn *Tuple7[XRef[HeroCfgID, HeroCfg], enums.HeroClass, Duration, int16, float32, bool, string] `json:"bossSpawn"`
	// Camera offset
	CameraOffset Vec3[float32] `json:"cameraOffset"`
	// Grid size
	GridSize Vec2[int32] `json:"gridSize"`
	// Tint
	Tint Vec4[float32] `json:"tint"`
	// World bounds
	WorldBounds Vec4[int32] `json:"worldBounds"`
}

// region Trifles

func (x *GameCfg) bindRefs(atlas *ConfigAtlas) {
	x.StartHero.Ref = atlas.HeroTable.Lookup(x.StartHero.CfgID)
	for i, v1 := range x.StarterItems {
		x.StarterItems[i].Ref = atlas.ItemTable.Lookup(v1.CfgID)
	}
	for i, v1 := range x.LevelRewards {
		x.LevelRewards[i] = makeXRef(v1.CfgID, atlas.ItemTable.Lookup(v1.CfgID))
	}
	if f := x.BossSpawn; f != nil {
		f.Item0.Ref = atlas.HeroTable.Lookup(f.Item0.CfgID)
	}
}

// endregion
