// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/hero.xlsx

package conf

import "time"
import "shadop.dev/pkg/sdk-go/internal/enums"

type HeroCfgID int64

type HeroTable map[HeroCfgID]*HeroCfg

type HeroCfg struct {
	ID HeroCfgID `json:"id"`
	// Hero name
	Name L10n `json:"name"`
	// Title
	Title string `json:"title"`
	// Class
	Class enums.HeroClass `json:"class"`
	// Elements
	Elements enums.Element `json:"elements"`
	// Level
	Level uint8 `json:"level"`
	// Luck
	Luck int8 `json:"luck"`
	// Rank
	Rank int16 `json:"rank"`
	// Hit points
	Hp int32 `json:"hp"`
	// Mana
	Mp uint16 `json:"mp"`
	// Fame
	Fame uint32 `json:"fame"`
	// Gold
	Gold int64 `json:"gold"`
	// Experience
	Exp uint64 `json:"exp"`
	// Power
	Power int `json:"power"`
	// Souls
	Souls uint `json:"souls"`
	// Critical rate
	CritRate float32 `json:"critRate"`
	// Dodge
	Dodge float64 `json:"dodge"`
	// Move speed
	MoveSpeed float64 `json:"moveSpeed"`
	Stats     *Stats  `json:"stats"`
	Growth    *Stats  `json:"growth"`
	// Birthday
	Birthday time.Time `json:"birthday"`
	// Respawn time
	Respawn Duration `json:"respawn"`
	// Theme color
	ThemeColor RGBA `json:"themeColor"`
	// Portrait
	Portrait string `json:"portrait"`
	// Playable
	Playable bool `json:"playable"`
	// Weapon
	Weapon XRef[ItemCfgID, ItemCfg] `json:"weapon"`
	// Weapon ID
	WeaponId int64 `json:"weaponId"`
	// Race
	Race XRef[RaceCfgID, RaceCfg] `json:"race"`
	// Spawn position
	SpawnPos Vec3[int32] `json:"spawnPos"`
	// Facing
	Facing Vec2[float32] `json:"facing"`
	// Talents
	Talents []*hero_TalentsEntry `json:"talents"`
}

// Stats represents $.*.stats
type Stats struct {
	// Base HP
	Hp int32 `json:"hp"`
	// Base attack
	Atk float32 `json:"atk"`
}

// hero_TalentsEntry represents $.*.talents.*
type hero_TalentsEntry struct {
	// Skill
	Skill XRef[SkillCfgID, SkillCfg] `json:"skill"`
	// Tier
	Tier int8 `json:"tier"`
}

func (x HeroTable) TryLookup(cfgID HeroCfgID) (*HeroCfg, error) {
	return xTryLookup[HeroCfgID, *HeroCfg](cfgID, x, "HeroTable")
}

func (x HeroTable) Lookup(cfgID HeroCfgID) *HeroCfg {
	return xLookup[HeroCfgID, *HeroCfg](cfgID, x, "HeroTable")
}

// region Trifles

func (x HeroCfgID) Cfg() *HeroCfg {
	return GetConfigAtlas().HeroTable[x]
}

func (x HeroTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x HeroTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *HeroCfg) bindRefs(atlas *ConfigAtlas) {
	x.Weapon.Ref = atlas.ItemTable.Lookup(x.Weapon.CfgID)
	x.Race.Ref = atlas.RaceTable.Lookup(x.Race.CfgID)
	for _, v1 := range x.Talents {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *hero_TalentsEntry) bindRefs(atlas *ConfigAtlas) {
	x.Skill.Ref = atlas.SkillTable.Lookup(x.Skill.CfgID)
}

// endregion
