// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/item.xlsx

package conf

import "shadop.dev/pkg/sdk-go/internal/enums"

type ItemCfgID int64

type ItemTable map[ItemCfgID]*ItemCfg

type ItemCfg struct {
	ID ItemCfgID `json:"id"`
	// Item name
	Name string `json:"name"`
	// Rarity
	Rarity enums.Rarity `json:"rarity"`
	// Price
	Price *Price `json:"price"`
	// Sell price
	SellPrice *Price `json:"sellPrice"`
	// Tags
	Tags []string `json:"tags"`
	// Icon
	Icon string `json:"icon"`
	// Stackable
	Stackable bool `json:"stackable"`
	// Best owner
	BestOwner XRef[HeroCfgID, HeroCfg] `json:"bestOwner"`
	// Enchantments
	Enchants []*item_EnchantsEntry `json:"enchants"`
}

// Price represents $.*.price
type Price struct {
	Gold int32 `json:"gold"`
	Gem  int16 `json:"gem"`
}

// item_EnchantsEntry represents $.*.enchants.*
type item_EnchantsEntry struct {
	// Element
	Element enums.Element `json:"element"`
	// Bonus
	Bonus int16 `json:"bonus"`
	// Scroll
	Scroll XRef[ItemCfgID, ItemCfg] `json:"scroll"`
}

func (x ItemTable) TryLookup(cfgID ItemCfgID) (*ItemCfg, error) {
	return xTryLookup[ItemCfgID, *ItemCfg](cfgID, x, "ItemTable")
}

func (x ItemTable) Lookup(cfgID ItemCfgID) *ItemCfg {
	return xLookup[ItemCfgID, *ItemCfg](cfgID, x, "ItemTable")
}

// region Trifles

func (x ItemCfgID) Cfg() *ItemCfg {
	return GetConfigAtlas().ItemTable[x]
}

func (x ItemTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x ItemTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *ItemCfg) bindRefs(atlas *ConfigAtlas) {
	x.BestOwner.Ref = atlas.HeroTable.Lookup(x.BestOwner.CfgID)
	for _, v1 := range x.Enchants {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *item_EnchantsEntry) bindRefs(atlas *ConfigAtlas) {
	x.Scroll.Ref = atlas.ItemTable.Lookup(x.Scroll.CfgID)
}

// endregion
