// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Item

package conf

type ItemTable map[ItemCfgID]*ItemCfg

type ItemCfg struct {
	ID    ItemCfgID   `json:"id"`
	Name  string      `json:"name"`
	Price *item_Price `json:"price"`
}

// item_Price represents $.*.price
type item_Price struct {
	One   int `json:"one"`
	Stack int `json:"stack"`
}

func (x ItemTable) TryLookup(cfgID ItemCfgID) (*ItemCfg, error) {
	return xTryLookup[ItemCfgID, *ItemCfg](cfgID, x, "ItemTable")
}

func (x ItemTable) Lookup(cfgID ItemCfgID) *ItemCfg {
	return xLookup[ItemCfgID, *ItemCfg](cfgID, x, "ItemTable")
}

// region Trifles

type ItemCfgID int

func (x ItemTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
