// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Magic

package conf

type MagicCfgID int64

type MagicTable map[MagicCfgID]*MagicCfg

type MagicCfg struct {
	ID   MagicCfgID `json:"id"`
	Name string     `json:"name"`
}

func (x MagicTable) TryLookup(cfgID MagicCfgID) (*MagicCfg, error) {
	return xTryLookup[MagicCfgID, *MagicCfg](cfgID, x, "MagicTable")
}

func (x MagicTable) Lookup(cfgID MagicCfgID) *MagicCfg {
	return xLookup[MagicCfgID, *MagicCfg](cfgID, x, "MagicTable")
}

// region Trifles

func (x MagicCfgID) Cfg() *MagicCfg {
	return GetConfigAtlas().MagicTable[x]
}

func (x MagicTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
