// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/matrix2.js

package conf

type Matrix2Table map[string]map[string][][]XRef[HeroCfgID, HeroCfg]

// region Trifles

func (x Matrix2Table) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		for _, v2 := range v1 {
			for _, v3 := range v2 {
				for i, v4 := range v3 {
					v3[i].Ref = atlas.HeroTable.Lookup(v4.CfgID)
				}
			}
		}
	}
}

// endregion
