// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/monster.json

package conf

import "shadop.dev/pkg/sdk-go/internal/enums"

type MonsterCfgID int

type MonsterTable map[MonsterCfgID]*MonsterCfg

type MonsterCfg struct {
	ID      MonsterCfgID                            `json:"id"`
	Name    string                                  `json:"name"`
	Habitat XRef[RegionCfgID, RegionCfg]            `json:"habitat"`
	Resist  map[enums.Element]int64                 `json:"resist"`
	Size    []float32                               `json:"size"`
	Speed   Vec2[float32]                           `json:"speed"`
	Aggro   MinMax[float32]                         `json:"aggro"`
	Loot    *WeightedPool[XRef[ItemCfgID, ItemCfg]] `json:"loot"`
	Stats   *monster_Stats                          `json:"stats"`
	Phases  []*monster_PhasesEntry                  `json:"phases"`
}

// monster_Stats represents $.*.stats
type monster_Stats struct {
	Hp  int64   `json:"hp"`
	Atk float64 `json:"atk"`
}

// monster_PhasesEntry represents $.*.phases.*
type monster_PhasesEntry struct {
	HpBelow int64                          `json:"hpBelow"`
	Summon  XRef[MonsterCfgID, MonsterCfg] `json:"summon"`
	Cast    XRef[SkillCfgID, SkillCfg]     `json:"cast"`
}

func (x MonsterTable) TryLookup(cfgID MonsterCfgID) (*MonsterCfg, error) {
	return xTryLookup[MonsterCfgID, *MonsterCfg](cfgID, x, "MonsterTable")
}

func (x MonsterTable) Lookup(cfgID MonsterCfgID) *MonsterCfg {
	return xLookup[MonsterCfgID, *MonsterCfg](cfgID, x, "MonsterTable")
}

// region Trifles

func (x MonsterCfgID) Cfg() *MonsterCfg {
	return GetConfigAtlas().MonsterTable[x]
}

func (x MonsterTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x MonsterTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *MonsterCfg) bindRefs(atlas *ConfigAtlas) {
	x.Habitat.Ref = atlas.RegionTable.Lookup(x.Habitat.CfgID)
	if f := x.Loot; f != nil {
		for i, ref := range f.Items {
			f.Items[i].Ref = atlas.ItemTable.Lookup(ref.CfgID)
		}
	}
	for _, v1 := range x.Phases {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *monster_PhasesEntry) bindRefs(atlas *ConfigAtlas) {
	x.Summon.Ref = atlas.MonsterTable.Lookup(x.Summon.CfgID)
	x.Cast.Ref = atlas.SkillTable.Lookup(x.Cast.CfgID)
}

// endregion
