// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/prop_floats.xlsx

package conf

type PropFloatsCfg struct {
	// desc-B
	B float64 `json:"B"`
	// desc-C
	C float32 `json:"C"`
	// desc-D
	D float64 `json:"D"`
	// desc-E
	E float32 `json:"E"`
	// desc-F
	F float64 `json:"F"`
	// desc-G
	G float64 `json:"G"`
}

// region Trifles

// endregion
