// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/world.xlsx::Race

package conf

type RaceCfgID string

type RaceTable map[RaceCfgID]*RaceCfg

type RaceCfg struct {
	ID RaceCfgID `json:"id"`
	// Birthplace
	Birthplace L10n `json:"birthplace"`
	// Heroes
	Heroes []XRef[HeroCfgID, HeroCfg] `json:"heroes"`
	// Hero IDs
	HeroIds []int64 `json:"heroIds"`
}

func (x RaceTable) TryLookup(cfgID RaceCfgID) (*RaceCfg, error) {
	return xTryLookup[RaceCfgID, *RaceCfg](cfgID, x, "RaceTable")
}

func (x RaceTable) Lookup(cfgID RaceCfgID) *RaceCfg {
	return xLookup[RaceCfgID, *RaceCfg](cfgID, x, "RaceTable")
}

// region Trifles

func (x RaceCfgID) Cfg() *RaceCfg {
	return GetConfigAtlas().RaceTable[x]
}

func (x RaceTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x RaceTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RaceCfg) bindRefs(atlas *ConfigAtlas) {
	for i, ref := range x.Heroes {
		x.Heroes[i].Ref = atlas.HeroTable.Lookup(ref.CfgID)
	}
}

// endregion
