// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Race

package conf

type RaceCfgID string

type RaceTable map[RaceCfgID]*RaceCfg

type RaceCfg struct {
	ID         RaceCfgID                    `json:"id"`
	Birthplace L10n                         `json:"birthplace"`
	Referrer1  XRef[RefCfgID, RefCfg]       `json:"referrer1"`
	Referrer2  XRef[StringCfgID, StringCfg] `json:"referrer2"`
	Heroes1    []XRef[HeroCfgID, HeroCfg]   `json:"heroes1"`
	Heroes2    []XRef[HeroCfgID, HeroCfg]   `json:"heroes2"`
}

func (x RaceTable) TryLookup(cfgID RaceCfgID) (*RaceCfg, error) {
	return xTryLookup[RaceCfgID, *RaceCfg](cfgID, x, "RaceTable")
}

func (x RaceTable) Lookup(cfgID RaceCfgID) *RaceCfg {
	return xLookup[RaceCfgID, *RaceCfg](cfgID, x, "RaceTable")
}

// region Trifles

func (x RaceTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x RaceTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RaceCfg) bindRefs(atlas *ConfigAtlas) {
	x.Referrer1.Ref = atlas.RefTable.Lookup(x.Referrer1.CfgID)
	x.Referrer2.Ref = atlas.StringTable.Lookup(x.Referrer2.CfgID)
	for i, ref := range x.Heroes1 {
		x.Heroes1[i].Ref = atlas.HeroTable.Lookup(ref.CfgID)
	}
	for i, ref := range x.Heroes2 {
		x.Heroes2[i].Ref = atlas.HeroTable.Lookup(ref.CfgID)
	}
}

// endregion
