// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/ref.xlsx

package conf

type RefTable map[RefCfgID]*RefCfg

type RefCfg struct {
	ID RefCfgID `json:"id"`
	// desc-B
	B XRef[WeaponRuneCfgID, WeaponRuneCfg] `json:"B"`
	// desc-C
	C int `json:"C"`
	// desc-D
	D XRef[ItemCfgID, ItemCfg] `json:"D"`
	// desc-E
	E XRef[MagicCfgID, MagicCfg] `json:"E"`
	// desc-F
	F XRef[RaceCfgID, RaceCfg] `json:"F"`
	// desc-G
	G XRef[HeroCfgID, HeroCfg] `json:"G"`
	// desc-H
	H []XRef[StringCfgID, StringCfg] `json:"H"`
	// desc-J
	J XRef[ItemCfgID, ItemCfg] `json:"J"`
	// desc-K
	K XRef[RaceCfgID, RaceCfg] `json:"K"`
}

func (x RefTable) TryLookup(cfgID RefCfgID) (*RefCfg, error) {
	return xTryLookup[RefCfgID, *RefCfg](cfgID, x, "RefTable")
}

func (x RefTable) Lookup(cfgID RefCfgID) *RefCfg {
	return xLookup[RefCfgID, *RefCfg](cfgID, x, "RefTable")
}

// region Trifles

type RefCfgID int

func (x RefTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x RefTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RefCfg) bindRefs(atlas *ConfigAtlas) {
	x.B.Ref = atlas.WeaponRuneTable.Lookup(x.B.RawValue)
	x.D.Ref = atlas.ItemTable.Lookup(x.D.RawValue)
	x.E.Ref = atlas.MagicTable.Lookup(x.E.RawValue)
	x.F.Ref = atlas.RaceTable.Lookup(x.F.RawValue)
	x.G.Ref = atlas.HeroTable.Lookup(x.G.RawValue)
	for i, v1 := range x.H {
		x.H[i].Ref = atlas.StringTable.Lookup(v1.RawValue)
	}
	x.J.Ref = atlas.ItemTable.Lookup(x.J.RawValue)
	x.K.Ref = atlas.RaceTable.Lookup(x.K.RawValue)
}

// endregion
