// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/ref.xlsx

package conf

type RefTable map[int]*RefCfg

type RefCfg struct {
	ID int                       `json:"-"`
	B  XRef[int, WeaponRuneCfg]  `json:"B"` // desc-B
	C  int                       `json:"C"` // desc-C
	D  XRef[int, ItemCfg]        `json:"D"` // desc-D
	E  XRef[int, MagicCfg]       `json:"E"` // desc-E
	F  XRef[string, RaceCfg]     `json:"F"` // desc-F
	G  XRef[int, HeroCfg]        `json:"G"` // desc-G
	H  []XRef[string, StringCfg] `json:"H"` // desc-H
	J  XRef[int, ItemCfg]        `json:"J"` // desc-J
	K  XRef[string, RaceCfg]     `json:"K"` // desc-K
}

func (x RefTable) TryLookup(cfgID int) (*RefCfg, error) {
	return xTryLookup[int, *RefCfg](cfgID, x, "RefTable")
}

func (x RefTable) Lookup(cfgID int) *RefCfg {
	return xLookup[int, *RefCfg](cfgID, x, "RefTable")
}

// region Trifles

func (x RefTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x RefTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RefCfg) bindRefs(atlas *ConfigAtlas) {
	x.B.Ref = atlas.WeaponRuneTable.Lookup(x.B.RawValue)
	x.D.Ref = atlas.ItemTable.Lookup(x.D.RawValue)
	x.E.Ref = atlas.MagicTable.Lookup(x.E.RawValue)
	x.F.Ref = atlas.RaceTable.Lookup(x.F.RawValue)
	x.G.Ref = atlas.HeroTable.Lookup(x.G.RawValue)
	for i, v1 := range x.H {
		x.H[i].Ref = atlas.StringTable.Lookup(v1.RawValue)
	}
	x.J.Ref = atlas.ItemTable.Lookup(x.J.RawValue)
	x.K.Ref = atlas.RaceTable.Lookup(x.K.RawValue)
}

// endregion
