// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/world.xlsx::Region

package conf

type RegionCfgID string

type RegionTable map[RegionCfgID]*RegionCfg

type RegionCfg struct {
	ID RegionCfgID `json:"id"`
	// Region name
	Name string `json:"name"`
	// Climate
	Climate string `json:"climate"`
	// Neighbors
	Neighbors []XRef[RegionCfgID, RegionCfg] `json:"neighbors"`
	// Monsters
	Monsters []XRef[MonsterCfgID, MonsterCfg] `json:"monsters"`
}

func (x RegionTable) TryLookup(cfgID RegionCfgID) (*RegionCfg, error) {
	return xTryLookup[RegionCfgID, *RegionCfg](cfgID, x, "RegionTable")
}

func (x RegionTable) Lookup(cfgID RegionCfgID) *RegionCfg {
	return xLookup[RegionCfgID, *RegionCfg](cfgID, x, "RegionTable")
}

// region Trifles

func (x RegionCfgID) Cfg() *RegionCfg {
	return GetConfigAtlas().RegionTable[x]
}

func (x RegionTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x RegionTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *RegionCfg) bindRefs(atlas *ConfigAtlas) {
	for i, v1 := range x.Neighbors {
		x.Neighbors[i].Ref = atlas.RegionTable.Lookup(v1.CfgID)
	}
	for i, ref := range x.Monsters {
		x.Monsters[i].Ref = atlas.MonsterTable.Lookup(ref.CfgID)
	}
}

// endregion
