// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/route.js

package conf

type RouteTable map[string]map[string][][]XRef[RegionCfgID, RegionCfg]

// region Trifles

func (x RouteTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		for _, v2 := range v1 {
			for _, v3 := range v2 {
				for i, v4 := range v3 {
					v3[i].Ref = atlas.RegionTable.Lookup(v4.CfgID)
				}
			}
		}
	}
}

// endregion
