// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: skill (virtual table)

package conf

import "shadop.dev/pkg/sdk-go/internal/enums"

type SkillCfgID string

type SkillTable map[SkillCfgID]*SkillCfg

type SkillCfg struct {
	ID SkillCfgID `json:"id"`
	// Skill name
	Name string `json:"name"`
	// Cooldown
	Cooldown Duration `json:"cooldown"`
	// Mana cost
	Mana int32 `json:"mana"`
	// School
	School enums.Element `json:"school"`
	// Source
	Src string `json:"src"`
	// Damage
	Damage MinMax[int32] `json:"damage"`
	// Buffs
	Buffs  map[string]*skill_BuffsEntry `json:"buffs"`
	Radius float64                      `json:"radius"`
}

// skill_BuffsEntry represents $.*.buffs.*
type skill_BuffsEntry struct {
	// Stacks
	Stacks int8 `json:"stacks"`
	// Buff duration
	Time Duration `json:"time"`
	// Granted by
	Source XRef[ItemCfgID, ItemCfg] `json:"source"`
}

func (x SkillTable) TryLookup(cfgID SkillCfgID) (*SkillCfg, error) {
	return xTryLookup[SkillCfgID, *SkillCfg](cfgID, x, "SkillTable")
}

func (x SkillTable) Lookup(cfgID SkillCfgID) *SkillCfg {
	return xLookup[SkillCfgID, *SkillCfg](cfgID, x, "SkillTable")
}

// region Trifles

func (x SkillCfgID) Cfg() *SkillCfg {
	return GetConfigAtlas().SkillTable[x]
}

func (x SkillTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x SkillTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *SkillCfg) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x.Buffs {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *skill_BuffsEntry) bindRefs(atlas *ConfigAtlas) {
	x.Source.Ref = atlas.ItemTable.Lookup(x.Source.CfgID)
}

// endregion
