// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/string.xlsx

package conf

type StringCfgID string

type StringTable map[StringCfgID]*StringCfg

type StringCfg struct {
	ID StringCfgID `json:"id"`
	B  *string_B   `json:"B"`
	// desc-E
	E string `json:"E"`
	// def-validate
	DefValidate string `json:"def-validate"`
	// def-postprocess
	DefPostprocess string `json:"def-postprocess"`
	// desc-I
	I string `json:"I"`
	// desc-K
	K XRef[RaceCfgID, RaceCfg] `json:"K"`
	// desc-referer1
	Referer1 XRef[RefCfgID, RefCfg] `json:"referer1"`
	// desc-referer2
	Referer2 XRef[RefCfgID, RefCfg] `json:"referer2"`
	// desc-referer-n
	RefererN []XRef[RefCfgID, RefCfg] `json:"referer-n"`
}

// string_B represents $.*.B
type string_B struct {
	Bar *Rab `json:"bar"`
	// desc-B.car
	Car string `json:"car"`
}

// Rab represents $.*.B.bar
type Rab struct {
	// desc-B.bar.foo
	Foo string `json:"foo"`
	// desc-B.bar.qux
	Qux string `json:"qux"`
}

func (x StringTable) TryLookup(cfgID StringCfgID) (*StringCfg, error) {
	return xTryLookup[StringCfgID, *StringCfg](cfgID, x, "StringTable")
}

func (x StringTable) Lookup(cfgID StringCfgID) *StringCfg {
	return xLookup[StringCfgID, *StringCfg](cfgID, x, "StringTable")
}

// region Trifles

func (x StringCfgID) Cfg() *StringCfg {
	return GetConfigAtlas().StringTable[x]
}

func (x StringTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x StringTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *StringCfg) bindRefs(atlas *ConfigAtlas) {
	x.K.Ref = atlas.RaceTable.Lookup(x.K.CfgID)
	x.Referer1.Ref = atlas.RefTable.Lookup(x.Referer1.CfgID)
	x.Referer2.Ref = atlas.RefTable.Lookup(x.Referer2.CfgID)
	for i, ref := range x.RefererN {
		x.RefererN[i].Ref = atlas.RefTable.Lookup(ref.CfgID)
	}
}

// endregion
