// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtQuest (virtual table)

package conf

type VtQuestCfgID int64

type VtQuestTable map[VtQuestCfgID]*VtQuestCfg

type VtQuestCfg struct {
	ID              VtQuestCfgID     `json:"id"`
	Name            string           `json:"name"`
	ChosenBy        []int64          `json:"chosenBy"`
	NextQuest       int64            `json:"nextQuest"`
	Desc            L10n             `json:"desc"`
	Origin          string           `json:"origin"`
	UnlockedBy      int64            `json:"unlockedBy"`
	RefreshInterval MinMax[Duration] `json:"refreshInterval"`
}

func (x VtQuestTable) TryLookup(cfgID VtQuestCfgID) (*VtQuestCfg, error) {
	return xTryLookup[VtQuestCfgID, *VtQuestCfg](cfgID, x, "VtQuestTable")
}

func (x VtQuestTable) Lookup(cfgID VtQuestCfgID) *VtQuestCfg {
	return xLookup[VtQuestCfgID, *VtQuestCfg](cfgID, x, "VtQuestTable")
}

// region Trifles

func (x VtQuestCfgID) Cfg() *VtQuestCfg {
	return GetConfigAtlas().VtQuestTable[x]
}

func (x VtQuestTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
