// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: vtQuest (virtual table)

package conf

type VtQuestCfgID int64

type VtQuestTable map[VtQuestCfgID]*VtQuestCfg

type VtQuestCfg struct {
	ID              VtQuestCfgID                     `json:"id"`
	Name            string                           `json:"name"`
	ChosenBy        []XRef[VtQuestCfgID, VtQuestCfg] `json:"chosenBy"`
	NextQuest       XRef[VtQuestCfgID, VtQuestCfg]   `json:"nextQuest"`
	Desc            L10n                             `json:"desc"`
	Origin          string                           `json:"origin"`
	UnlockedBy      XRef[VtQuestCfgID, VtQuestCfg]   `json:"unlockedBy"`
	RefreshInterval MinMax[Duration]                 `json:"refreshInterval"`
}

func (x VtQuestTable) TryLookup(cfgID VtQuestCfgID) (*VtQuestCfg, error) {
	return xTryLookup[VtQuestCfgID, *VtQuestCfg](cfgID, x, "VtQuestTable")
}

func (x VtQuestTable) Lookup(cfgID VtQuestCfgID) *VtQuestCfg {
	return xLookup[VtQuestCfgID, *VtQuestCfg](cfgID, x, "VtQuestTable")
}

// region Trifles

func (x VtQuestCfgID) Cfg() *VtQuestCfg {
	return GetConfigAtlas().VtQuestTable[x]
}

func (x VtQuestTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x VtQuestTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *VtQuestCfg) bindRefs(atlas *ConfigAtlas) {
	for i, ref := range x.ChosenBy {
		x.ChosenBy[i].Ref = atlas.VtQuestTable.Lookup(ref.CfgID)
	}
	x.NextQuest.Ref = atlas.VtQuestTable.Lookup(x.NextQuest.CfgID)
	x.UnlockedBy.Ref = atlas.VtQuestTable.Lookup(x.UnlockedBy.CfgID)
}

// endregion
