// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtSkill (virtual table)

package conf

type VtSkillCfgID string

type VtSkillTable map[VtSkillCfgID]*VtSkillCfg

type VtSkillCfg struct {
	ID    VtSkillCfgID              `json:"id"`
	Name  string                    `json:"name"`
	Class string                    `json:"class"`
	Foo   map[int]*vtSkill_FooEntry `json:"Foo"`
	// reagent
	Reagent     int64   `json:"reagent"`
	CrossSkill1 string  `json:"cross-skill1"`
	Weapons     []int64 `json:"weapons"`
	CrossSkill2 string  `json:"cross-skill2"`
}

// vtSkill_FooEntry represents $.*.Foo.*
type vtSkill_FooEntry struct {
	// X1a
	X1 string   `json:"X1"`
	X2 Duration `json:"X2"`
	// X5
	X5 int `json:"X5"`
}

func (x VtSkillTable) TryLookup(cfgID VtSkillCfgID) (*VtSkillCfg, error) {
	return xTryLookup[VtSkillCfgID, *VtSkillCfg](cfgID, x, "VtSkillTable")
}

func (x VtSkillTable) Lookup(cfgID VtSkillCfgID) *VtSkillCfg {
	return xLookup[VtSkillCfgID, *VtSkillCfg](cfgID, x, "VtSkillTable")
}

// region Trifles

func (x VtSkillCfgID) Cfg() *VtSkillCfg {
	return GetConfigAtlas().VtSkillTable[x]
}

func (x VtSkillTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
