// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: vtSkill (virtual table)

package conf

type VtSkillCfgID string

type VtSkillTable map[VtSkillCfgID]*VtSkillCfg

type VtSkillCfg struct {
	ID    VtSkillCfgID              `json:"id"`
	Name  string                    `json:"name"`
	Class string                    `json:"class"`
	Foo   map[int]*vtSkill_FooEntry `json:"Foo"`
	// reagent
	Reagent     XRef[VtItemXCfgID, VtItemXCfg]   `json:"reagent"`
	CrossSkill1 XRef[VtSkillCfgID, VtSkillCfg]   `json:"cross-skill1"`
	Weapons     []XRef[VtItemXCfgID, VtItemXCfg] `json:"weapons"`
	CrossSkill2 XRef[VtSkillCfgID, VtSkillCfg]   `json:"cross-skill2"`
}

// vtSkill_FooEntry represents $.*.Foo.*
type vtSkill_FooEntry struct {
	// X1a
	X1 string   `json:"X1"`
	X2 Duration `json:"X2"`
	// X5
	X5 int `json:"X5"`
}

func (x VtSkillTable) TryLookup(cfgID VtSkillCfgID) (*VtSkillCfg, error) {
	return xTryLookup[VtSkillCfgID, *VtSkillCfg](cfgID, x, "VtSkillTable")
}

func (x VtSkillTable) Lookup(cfgID VtSkillCfgID) *VtSkillCfg {
	return xLookup[VtSkillCfgID, *VtSkillCfg](cfgID, x, "VtSkillTable")
}

// region Trifles

func (x VtSkillCfgID) Cfg() *VtSkillCfg {
	return GetConfigAtlas().VtSkillTable[x]
}

func (x VtSkillTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

func (x VtSkillTable) bindRefs(atlas *ConfigAtlas) {
	for _, v1 := range x {
		if v1 != nil {
			v1.bindRefs(atlas)
		}
	}
}

func (x *VtSkillCfg) bindRefs(atlas *ConfigAtlas) {
	x.Reagent.Ref = atlas.VtItemXTable.Lookup(x.Reagent.CfgID)
	x.CrossSkill1.Ref = atlas.VtSkillTable.Lookup(x.CrossSkill1.CfgID)
	for i, v1 := range x.Weapons {
		x.Weapons[i].Ref = atlas.VtItemXTable.Lookup(v1.CfgID)
	}
	x.CrossSkill2.Ref = atlas.VtSkillTable.Lookup(x.CrossSkill2.CfgID)
}

// endregion
