// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/weapon-rune.xlsx

package conf

type WeaponRuneTable map[WeaponRuneCfgID]*WeaponRuneCfg

type WeaponRuneCfg struct {
	ID       WeaponRuneCfgID `json:"id"`
	RuneName string          `json:"runeName"`
	Power    int             `json:"power"`
}

func (x WeaponRuneTable) TryLookup(cfgID WeaponRuneCfgID) (*WeaponRuneCfg, error) {
	return xTryLookup[WeaponRuneCfgID, *WeaponRuneCfg](cfgID, x, "WeaponRuneTable")
}

func (x WeaponRuneTable) Lookup(cfgID WeaponRuneCfgID) *WeaponRuneCfg {
	return xLookup[WeaponRuneCfgID, *WeaponRuneCfg](cfgID, x, "WeaponRuneTable")
}

// region Trifles

type WeaponRuneCfgID int

func (x WeaponRuneTable) ApplyKeys() {
	for k, v := range x {
		if v != nil {
			v.ID = k
		}
	}
}

// endregion
