// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source File: examples/conf/sdk/sdk.enum.yml
// Source File MD5: 737dea217ecdbcfea465569008dd7a54

// Enums for the SDK integration test data.

package enums

import (
	"fmt"
	"strconv"
	"strings"
)

var (
	_ *fmt.Stringer
	_ *strconv.NumError
	_ *strings.Builder
)

// region HeroClass

// Playable hero classes.
type HeroClass int32

const (
	HeroClassNone    HeroClass = 0
	HeroClassWarrior HeroClass = 1
	HeroClassMage    HeroClass = 2
	HeroClassRanger  HeroClass = 3
	HeroClassPriest  HeroClass = 4
)

var _heroClassNameMap = map[HeroClass]string{
	HeroClassNone:    "None",
	HeroClassWarrior: "Warrior",
	HeroClassMage:    "Mage",
	HeroClassRanger:  "Ranger",
	HeroClassPriest:  "Priest",
}

var _insensitiveNameHeroClassMap = map[string]HeroClass{
	"none":    HeroClassNone,
	"warrior": HeroClassWarrior,
	"mage":    HeroClassMage,
	"ranger":  HeroClassRanger,
	"priest":  HeroClassPriest,
}

var _heroClassValues = [...]HeroClass{
	HeroClassNone,
	HeroClassWarrior,
	HeroClassMage,
	HeroClassRanger,
	HeroClassPriest,
}

var _heroClassL10nKeyMap = map[HeroClass]string{
	HeroClassWarrior: "enum::HeroClass.Warrior",
	HeroClassMage:    "enum::HeroClass.Mage",
}

func HeroClassValues() []HeroClass {
	return _heroClassValues[:]
}

func ParseHeroClass(str string) (HeroClass, error) {
	str = strings.TrimSpace(str)
	if str == "" {
		return 0, fmt.Errorf("HeroClass: str is empty or whitespace")
	}
	lower := strings.ToLower(str)
	if v, ok := _insensitiveNameHeroClassMap[lower]; ok {
		return v, nil
	}
	s := str
	if strings.HasPrefix(lower, "heroclass(") && strings.HasSuffix(lower, ")") {
		s = str[10 : len(str)-1]
	}
	n, err := strconv.ParseInt(s, 0, 64)
	if err == nil {
		if n < -2147483648 || n > 2147483647 {
			return 0, fmt.Errorf("HeroClass: %d is out of range", n)
		}
		return (HeroClass)(n), nil
	}

	return 0, fmt.Errorf("HeroClass: invalid value %q", str)
}

func (x HeroClass) IsValid() bool {
	_, ok := _heroClassNameMap[x]
	return ok
}

func (x HeroClass) String() string {
	if str, ok := _heroClassNameMap[x]; ok {
		return str
	}
	return fmt.Sprintf("HeroClass(%d)", x)
}

func (x HeroClass) L10nKey() string {
	if key, ok := _heroClassL10nKeyMap[x]; ok {
		return key
	}
	return ""
}

// endregion

// region Rarity

type Rarity uint8

const (
	RarityCommon    Rarity = 0
	RarityUncommon  Rarity = 1
	RarityRare      Rarity = 2
	RarityEpic      Rarity = 3
	RarityLegendary Rarity = 4
)

var _rarityNameMap = map[Rarity]string{
	RarityCommon:    "Common",
	RarityUncommon:  "Uncommon",
	RarityRare:      "Rare",
	RarityEpic:      "Epic",
	RarityLegendary: "Legendary",
}

var _insensitiveNameRarityMap = map[string]Rarity{
	"common":    RarityCommon,
	"uncommon":  RarityUncommon,
	"rare":      RarityRare,
	"epic":      RarityEpic,
	"legendary": RarityLegendary,
}

var _rarityValues = [...]Rarity{
	RarityCommon,
	RarityUncommon,
	RarityRare,
	RarityEpic,
	RarityLegendary,
}

func RarityValues() []Rarity {
	return _rarityValues[:]
}

func ParseRarity(str string) (Rarity, error) {
	str = strings.TrimSpace(str)
	if str == "" {
		return 0, fmt.Errorf("Rarity: str is empty or whitespace")
	}
	lower := strings.ToLower(str)
	if v, ok := _insensitiveNameRarityMap[lower]; ok {
		return v, nil
	}
	s := str
	if strings.HasPrefix(lower, "rarity(") && strings.HasSuffix(lower, ")") {
		s = str[7 : len(str)-1]
	}
	n, err := strconv.ParseUint(s, 0, 64)
	if err == nil {
		if n > 255 {
			return 0, fmt.Errorf("Rarity: %d is out of range", n)
		}
		return (Rarity)(n), nil
	}

	return 0, fmt.Errorf("Rarity: invalid value %q", str)
}

func (x Rarity) IsValid() bool {
	_, ok := _rarityNameMap[x]
	return ok
}

func (x Rarity) String() string {
	if str, ok := _rarityNameMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Rarity(%d)", x)
}

// endregion

// region Element

type Element uint16

const (
	ElementNone   Element = 0x0
	ElementFire   Element = 0x1
	ElementWater  Element = 0x2
	ElementEarth  Element = 0x4
	ElementWind   Element = 0x8
	ElementHoly   Element = 0x10
	ElementShadow Element = 0x20
)

var _elementNameMap = map[Element]string{
	ElementNone:   "None",
	ElementFire:   "Fire",
	ElementWater:  "Water",
	ElementEarth:  "Earth",
	ElementWind:   "Wind",
	ElementHoly:   "Holy",
	ElementShadow: "Shadow",
}

var _insensitiveNameElementMap = map[string]Element{
	"none":   ElementNone,
	"fire":   ElementFire,
	"water":  ElementWater,
	"earth":  ElementEarth,
	"wind":   ElementWind,
	"holy":   ElementHoly,
	"shadow": ElementShadow,
}

var _elementValues = [...]Element{
	ElementNone,
	ElementFire,
	ElementWater,
	ElementEarth,
	ElementWind,
	ElementHoly,
	ElementShadow,
}

func ElementValues() []Element {
	return _elementValues[:]
}

func parseBitflagElement(str string, raw string) (Element, error) {
	var res Element
	for _, x := range strings.Split(str, ",") {
		x = strings.TrimSpace(x)
		if v, ok := _insensitiveNameElementMap[x]; ok {
			res |= v
			continue
		}
		return 0, fmt.Errorf("Element: invalid value %q", raw)
	}

	return res, nil
}

func ParseElement(str string) (Element, error) {
	str = strings.TrimSpace(str)
	if str == "" {
		return 0, fmt.Errorf("Element: str is empty or whitespace")
	}
	lower := strings.ToLower(str)
	if v, ok := _insensitiveNameElementMap[lower]; ok {
		return v, nil
	}
	if strings.IndexByte(lower, ',') >= 0 {
		return parseBitflagElement(lower, str)
	}
	s := str
	if strings.HasPrefix(lower, "element(") && strings.HasSuffix(lower, ")") {
		s = str[8 : len(str)-1]
	}
	n, err := strconv.ParseUint(s, 0, 64)
	if err == nil {
		if n > 65535 {
			return 0, fmt.Errorf("Element: %d is out of range", n)
		}
		return (Element)(n), nil
	}

	return 0, fmt.Errorf("Element: invalid value %q", str)
}

func (x Element) IsValid() bool {
	if _, ok := _elementNameMap[x]; ok {
		return true
	}
	for i := len(_elementValues) - 1; i >= 0 && x != 0; i-- {
		v := _elementValues[i]
		if (x & v) == v {
			x &= ^v
		}
	}
	return x == 0
}

func (x Element) String() string {
	if str, ok := _elementNameMap[x]; ok {
		return str
	}

	if x.IsValid() {
		var flags []Element
		for i := len(_elementValues) - 1; i >= 0 && x != 0; i-- {
			v := _elementValues[i]
			if v != 0 {
				if (x & v) == v {
					x &= ^v
					flags = append(flags, v)
				}
			}
		}

		var sb strings.Builder
		i := len(flags) - 1
		v := flags[i]
		_, _ = sb.WriteString(_elementNameMap[v])
		for i--; i >= 0; i-- {
			v = flags[i]
			_, _ = sb.WriteString(", ")
			_, _ = sb.WriteString(_elementNameMap[v])
		}
		return sb.String()
	}

	return fmt.Sprintf("Element(%d)", x)
}

// endregion
